// <auto-generated />
namespace Task_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Northwind11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Northwind11));
        
        string IMigrationMetadata.Id
        {
            get { return "202006131809025_Northwind1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
